-- MySQL Script generated by MySQL Workbench
-- Fri Nov 16 09:42:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet4` DEFAULT CHARACTER SET utf8 ;
USE `projet4` ;

-- -----------------------------------------------------
-- Table `projet4`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet4`.`Client` (
  `num_client` INT NOT NULL AUTO_INCREMENT,
  `prenom_client` VARCHAR(45) NOT NULL,
  `nom_client` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet4`.`Localisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet4`.`Localisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `voie` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(45) NULL,
  `code_postal` VARCHAR(5) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(10) NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet4`.`Livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet4`.`Livreur` (
  `num_livreur` INT NOT NULL AUTO_INCREMENT,
  `nom_livreur` VARCHAR(45) NOT NULL,
  `num_plats_en_stock` VARCHAR(45) NOT NULL,
  `statut` TINYINT(1) NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  PRIMARY KEY (`num_livreur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet4`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet4`.`Commande` (
  `num_commande` INT NOT NULL AUTO_INCREMENT,
  `date_commande` DATETIME NOT NULL,
  `montant_commande` DECIMAL(6,2) NOT NULL,
  `statut_commande` ENUM('en cours', 'livrée') NOT NULL,
  `num_client` INT NOT NULL,
  `num_livreur` INT NOT NULL,
  `Localisation_id` INT NOT NULL,
  PRIMARY KEY (`num_commande`),
  INDEX `fk_commande_Client_idx` (`num_client` ASC),
  INDEX `fk_commande_Livreur1_idx` (`num_livreur` ASC),
  INDEX `fk_Commande_Localisation1_idx` (`Localisation_id` ASC),
  CONSTRAINT `fk_commande_Client`
    FOREIGN KEY (`num_client`)
    REFERENCES `projet4`.`Client` (`num_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_Livreur1`
    FOREIGN KEY (`num_livreur`)
    REFERENCES `projet4`.`Livreur` (`num_livreur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Localisation1`
    FOREIGN KEY (`Localisation_id`)
    REFERENCES `projet4`.`Localisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet4`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet4`.`Produit` (
  `num_produit` INT NOT NULL AUTO_INCREMENT,
  `nom_produit` VARCHAR(45) NOT NULL,
  `type_produit` ENUM('plat', 'dessert') NOT NULL,
  `ingredients` VARCHAR(45) NOT NULL,
  `prix` DECIMAL(4,2) NOT NULL,
  `num_commande` INT NOT NULL,
  PRIMARY KEY (`num_produit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet4`.`Produits_dans_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet4`.`Produits_dans_commande` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Commande_num_commande` INT NOT NULL,
  `Produit_num_produit` INT NOT NULL,
  `quantite_produits` INT NOT NULL,
  INDEX `fk_Commande_has_Produit_Produit1_idx` (`Produit_num_produit` ASC),
  INDEX `fk_Commande_has_Produit_Commande1_idx` (`Commande_num_commande` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Commande_has_Produit_Commande1`
    FOREIGN KEY (`Commande_num_commande`)
    REFERENCES `projet4`.`Commande` (`num_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Produit_Produit1`
    FOREIGN KEY (`Produit_num_produit`)
    REFERENCES `projet4`.`Produit` (`num_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
